# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

target "NineBoard-ios" do

pod "AFNetworking", "~> 2.0"
pod 'Facebook-iOS-SDK', '~> 3.16.2'

end

target "NineBoard-iosTests" do

end

